server:
  port: 8080

oauth:
  appClients:
    -
      clientId: app1Client
      clientSecret: app1Secret
      authorizedGrantTypes:
        - password
        - refresh_token
        - client_credentials
      authorities:
        - ROLE_CLIENT
        - ROLE_TRUSTED_CLIENT
      scopes:
        - read
        - write
        - trust