server:
  port: 8080

oauth:
  appClients:
    -
      clientId: exampleClient
      clientSecret: "{noop}exampleSecret"
      authorizedGrantTypes:
        - password
        - refresh_token
        - client_credentials
      authorities:
        - ROLE_CLIENT
        - ROLE_TRUSTED_CLIENT
      scopes:
        - read
        - write
        - trust